version: "3.8"

services:
  webapp:
    image: golang:1.23-alpine  # Use an official Go image
    container_name: olympus
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 of the host
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    working_dir: /app  # Set the working directory to /app
    environment:
      - CGO_ENABLED=1
    command: > 
      sh -c "
      apk update && apk add sqlite-dev gcc libc-dev && go run .
      "