version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: matchmaking_redis
    restart: always
    ports:
      - "6379:6379"

  matchmaking_server:
    build:
      context: .
      dockerfile: Dockerfile  # Reference the separate Dockerfile
    container_name: matchmaking_server
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:8080"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - matchmaking_server
    ports:
      - "9090:9090"
    command:
    - "--log.level=error"  # Set the log level to debug
    - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
    - GF_LOG_LEVEL=error
    volumes:
      - ./grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data: