version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"

  go_server:
    build:
      context: .
      dockerfile: Dockerfile  # Reference the separate Dockerfile
    container_name: go_server
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:8080"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - go_server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data: